### ISSUE TITLE
你的个和官方最新的0.11.10不一样喔

### ISSUE THREAD

**Issue by zengsuyi** [daimiao/voyager-zh#1]
- Laravel Version: #.#.#5.4
- Voyager Version: #.#.#0.11.10
- PHP Version:7.0
- Database Driver & Version:mysql5.7

### Description:
我安装官方得0.11.10可以完美运行在laravel5.4上 
当我替换你这个后 有很多差别  运行不起来

**Comment by daimiao** [comment]
具体有什么错误提示？

**Comment by zengsuyi** [comment]
<?php
namespace TCG\Voyager\Commands;
use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Symfony\Component\Console\Input\InputOption;
class ControllersCommand extends Command
{
    /**
     * The console command name.
     *
     * @var string
     */
    protected $name = 'voyager:controllers';
    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Publish all the controllers from Voyager.';
    /**
     * The Filesystem instance.
     *
     * @var Filesystem
     */
    protected $filesystem;
    /**
     * Filename of stub-file.
     *
     * @var string
     */
    protected $stub = 'controller.stub'; 
比如这个文件就不一样。
其他地方我没看了。一直提示错误。

**Comment by zengsuyi** [comment]
<?php
namespace TCG\Voyager\Commands;
use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Symfony\Component\Console\Input\InputOption;
class ControllersCommand extends Command
{
    /**
     * The console command name.
     *
     * @var string
     */
    protected $name = 'voyager:controllers';
    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Publish all the controllers from Voyager.';
    /**
     * The Filesystem instance.
     *
     * @var Filesystem
     */
    protected $filesystem;
    /**
     * Filename of stub-file.
     *
     * @var string
     */
    protected $stub = 'controller.stub';

**Comment by zengsuyi** [comment]
namespace TCG\Voyager\Commands;
use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Symfony\Component\Console\Input\InputOption;
class ControllersCommand extends Command


这个文件就不一样  其他得没看了  从这个文件就可以看出你这个不支持5.4
但是官方最新的0.11.10确实适配了5.4的

**Comment by daimiao** [comment]
说明写错了，应该是voyagerv0.11.09版本，很快我就会翻译最新版的
