### ISSUE TITLE
安装了voyagerv0.11.10用你的代码覆盖了会报Class admin.user does not exist

### ISSUE THREAD

**Issue by xusenlin** [daimiao/voyager-zh#2]
- Laravel Version: 5.4.*
- Voyager Version: ^0.11.10
- PHP Version:>=5.6.4
- Database Driver & Version:
   mysql 
### Description:
  安装了voyagerv0.11.10用你的代码覆盖了会报admin.user类找不到
  ReflectionException in Container.php line 719:
  Class admin.user does not exist

**Comment by daimiao** [comment]
说明写错了，应该是voyagerv0.11.09版本

**Comment by bajian** [comment]
voyagerv0.11.09 同样报的这个错。。Laravel Version: 5.4.24

**Comment by xusenlin** [comment]
我自己翻译了一个，欢迎使用。https://github.com/xusenlin/voyager
